---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: comment
  labels:
    app: reddit
    component: comment
    ui-comment: "true"
  name: comment-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reddit
      component: comment
  template:
    metadata:
      name: comment
      labels:
        app: reddit
        component: comment
        ui-comment: "true"
    spec:
      containers:
        - image: dvparshin/comment
          name: comment

          env:
            - name: COMMENT_DATABASE_HOST
              value: comment-db
